reliability:
  kubeconfig: ~/Downloads/kubeconfig
  timeSubstitutions:
    minute: 10s
    hour: 30s
    day: 2m
    week: 3m
    month: 4m
  limits:
    maxProjects: 20
    sleepTime: 10

  appTemplates:
    - template: cakephp-mysql-persistent
    - template: nodejs-postgresql-persistent
    - template: django-psql-persistent
    - template: rails-pgsql-persistent
    - template: dancer-mysql-persistent

  users:
    - admin_user: kubeadmin
    - admin_password: R3xrm-uIABR-BB4Za-xaWWF
    - user_file: /Users/qili/Downloads/users.spec
  tasks:
    minute:
      - action: check
        resource: pods
      - action: check
        resource: projects
      - action: create
        resource: projects
        quantity: 1
    hour:
      - action: check
        resource: projects
      - action: visit
        resource: apps
        applyPercent: 100
      - action: create
        resource: projects
        quantity: 1
      - action: scaleUp
        resource: apps
        applyPercent: 50
      - action: scaleDown
        resource: apps
        applyPercent: 50
      - action: build
        resource: apps
        applyPercent: 33
      - action: modify
        resource: projects
        applyPercent: 25
    week:
      - action: delete
        resource: projects
        applyPercent: 25
      - action: login
        resource: session
        user: testuser-47
        password: LNrHdFaoJh9X

