provider: local
ClusterLoader:
  cleanup: true
  projects:
    - num: 1
      basename: clusterproject
      tuning: default
      ifexists: delete
      pods:
        - num: 660
          basename: hello
          file: ../../content/pod-pause-labeled-nodes.json
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 50
          pause: 60
        ratelimit:
          delay: 0
