provider: local
ClusterLoader:
  cleanup: false
  projects:
    - num: 1
      basename: taints-tolerationss1-
      ifexists: delete
      tuning: default
      pods:
        - num: 200
          image: docker.io/ocpqe/hello-pod
          basename: hellopods-taints-s1
          file: ./content/pod-hello-s1-taints-tolerations.json

    - num: 1
      basename: taints-tolerationss2-
      ifexists: delete
      tuning: default
      pods:
        - num: 200
          image: docker.io/ocpqe/hello-pod
          basename: hellopods-taints-s2
          file: ./content/pod-hello-s2-taints-tolerations.json
    
    - num: 1
      basename: taints-tolerationss3-
      ifexists: delete
      tuning: default
      pods:
        - num: 200
          image: docker.io/ocpqe/hello-pod
          basename: hellopods-taints-s3
          file: ./content/pod-hello-s3-taints-tolerations.json

  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 50
          pause: 15
        ratelimit:
          delay: 0
