provider: local
ClusterLoader:
  cleanup: false
  projects:
    - num: 1
      basename: taints-tolerationss1-
      tuning: default
      ifexists: delete
      pods:
        - num: 130
          image: docker.io/ocpqe/hello-pod
          basename: hellopods-taints-s1
          file: /root/svt/openshift_scalability/content/pod-hello-s1-taints-tolerations.json

    - num: 1
      basename: taints-tolerationss2-
      tuning: default
      ifexists: delete
      pods:
        - num: 130
          image: docker.io/ocpqe/hello-pod
          basename: hellopods-taints-s2
          file: /root/svt/openshift_scalability/content/pod-hello-s2-taints-tolerations.json

  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 50
          pause: 120
        ratelimit:
          delay: 0
