apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-local
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/io
              operator: In
              values:
                - linux