jobs:
  - name: {{.NAME}}
    namespace: {{.NAMESPACE}}
    jobIterations: {{.JOB_ITERATION}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: true
    verifyObjects: true
    waitFor: {{.WAIT_FOR}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
    - objectTemplate: "deployment.yaml"
      replicas: 1
      inputVars:
        pod_replicas: {{.POD_REPLICAS}}