apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-anti-affinity-{{.Iteration}}
  labels:
    app: hello-pod-anti-affinity-{{.Iteration}}

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement
            operator: NotIn
            values:
            - affinity
  containers:
  - name: hello-pod
    image: gcr.io/google-containers/pause-amd64:3.0
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: true
      runAsUser: 2000
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always