jobs:
  - name: {{.NAME}}
    namespace: {{.NAMESPACE}}
    jobIterations: {{.JOB_ITERATION}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: true
    verifyObjects: true
    waitFor: {{.WAIT_FOR}}
    preLoadImages: false
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:
    - objectTemplate: "pause-pod.yaml"
      replicas: {{.POD_REPLICAS}}
    - objectTemplate: "image-stream.yaml"
      replicas: {{.IMAGES_STREAM_REPLICAS}}
      inputVars: 
        image: gcr.io/google_containers/pause-amd64
        name: pauseimagestream
    - objectTemplate: "image-stream.yaml"
      replicas:  {{.IMAGES_STREAM_REPLICAS}}
      inputVars: 
        image: openshift/hello-openshift
        name: 'imagestream'
    - objectTemplate: "build-config.yaml"
      replicas: {{.BUILDS_REPLICAS}}
      inputVars:
        git_image: quay.io/openshifttest/pause:latest
    - objectTemplate: "build.yaml"
      replicas: {{.BUILDS_REPLICAS}}
    - objectTemplate: ssh-secret.yaml
      replicas: {{.SECRETS_REPLICAS}}
    - objectTemplate: "route.yaml"
      replicas: {{.ROUTES_REPLICAS}}
