apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-test-{{.Iteration}}
  labels:
    app: node-affinity-test-{{.Iteration}}

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: Gt
            values:
            - '4'
  containers:
  - name: node-affinity
    image: gcr.io/google-containers/pause-amd64:3.0
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: true
      runAsUser: 2000
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always