apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovn-network-metrics
spec:
  replicas: {{.pod_replicas}}
  selector:
    matchLabels:
      app: ovn-network-metrics
  template:
    metadata:
      labels:
        app: ovn-network-metrics
    spec:
      containers:
      - image: openshift/hello-openshift:latest
        imagePullPolicy: IfNotPresent
        name: app-web