apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovn-lnp-pause
  name: ovn-lnp-pause-{{.Replica}}-{{.Iteration}}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ovn-lnp-pause-{{.Replica}}-{{.Iteration}}
  type: {{.serviceType}}