kind: Pod
apiVersion: v1
metadata:
  name: pausepod-{{.Replica}}-{{.Iteration}}
  creationTimestamp:
  labels:
    name: pause-amd64
spec:
  containers:
  - name: pause-amd64
    image: gcr.io/google_containers/pause-amd64:3.0
    ports:
    - containerPort: 8080
      protocol: TCP
    terminationMessagePath: "/dev/termination-log"
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}
