apiVersion: v1
kind: Pod
metadata:
  name: s1-test-pod
  labels:
    security: s1
spec:
  containers:
  - name: ocp
    image: gcr.io/google-containers/pause-amd64:3.0
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: true
      runAsUser: 2000
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always