apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-test-{{.Iteration}}
  labels:
    app: pod-anti-affinity-test-{{.Iteration}}

spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - s1
        namespaces:
        - s1-proj
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: gcr.io/google-containers/pause-amd64:3.0
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      runAsNonRoot: true
      runAsUser: 2000
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
