apiVersion: v1
kind: ReplicationController
metadata:
  name: rcexlc
spec:
  replicas: {{.pod_replicas}}
  selector:
    app: sise
  template:
    metadata:
      name: rc_local_storage
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/openshifttest/hello-openshift:1.2.0
        ports:
        - containerPort: 9876
        volumeMounts:
        - mountPath: /tmp
          name: task-pv-storage
      volumes:
      - name: task-pv-storage
        HostPath:
          path: /mnt/data
          type: DirectoryOrCreate