apiVersion: v1
kind: ReplicationController
metadata:
  name: rcexpv
spec:
  replicas: {{.pod_replicas}}
  selector:
    app: sise
  template:
    metadata:
      name: somename
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/openshifttest/hello-openshift:1.2.0
        ports:
        - containerPort: 9876
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /tmp
          name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim