apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-issue-test
spec:
  replicas: {{.pod_replicas}}
  selector:
    matchLabels:
      app: np-issue-test
  template:
    metadata:
      labels:
        app: np-issue-test
    spec:
      containers:
      - image: openshift/hello-openshift:latest
        imagePullPolicy: IfNotPresent
        name: app-web