projects:
  - num: 1
    basename: clusterproject
    ifexists: delete
    tuning: default
    pods:
      - total: 100
      - num: 660
        file: content/pod-pause.json
        basename: hello
        storage:
          - type: none

quotas:
  - name: default
    file: default

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 100
        pause: 10 s
      rate_limit:
        delay: 0 ms