apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  name: {{.name}}
spec:
  nodeSelector: {{.nodeSelector}}
  output:
    to:
      kind: ImageStreamTag
      name: {{.name}}:latest
  postCommit:
    script: ./vendor/bin/phpunit
  source:
    git:
      uri: {{.sourceGitUri}}
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: COMPOSER_MIRROR
      from:
        kind: ImageStreamTag
        name: "php:{{.phpVersion}}"
        namespace: openshift
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secret: {{.githubWebhookSecret}}
    