apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}
stringData:
  cakephp-secret-token: {{.cakephpSecretToken}}
  cakephp-security-salt: {{.cakephpSecuritySalt}}
  database-password: {{.databasePassword}}
  database-user: {{.databaseUser}}
  